version: "3"

services:
  mongo:
    image: mongo:latest
    volumes:
      - ./test_data:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=volvo

  calculator:
    depends_on:
      - mongo
    links:
      - mongo
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - MONGO_USER=admin
      - MONGO_PASSWORD=admin
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=volvo