version: "3"

services:
  db:
    image: mongodb:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD

  calculator:
    depends_on:
      - db
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"
      - "8081:8081"
